blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("post/new/", views.BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", views.BlogDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/edit/", views.BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", views.BlogDeleteView.as_view(), name="post_delete"),
    path("", views.BlogListView.as_view(), name="post_list"),
]

django_for_beginners/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("hello", include("hello_world.urls")),
    path("pages/", include("pages.urls")),
    path("messages/", include("message_board.urls")),
    path("blogs/", include("blog.urls")),
    path("newspaper/", include("newspaper.urls")),

    # API
    path("api/v1/", include("newspaper.api.urls")),
]

newspaper/api/urls.py
from django.urls import path

from . import views

# API endpoints for the newspaper app
urlpatterns = [
    path("users/", views.user_list, name="newspaper_user_list"),
    path("articles/", views.article_list, name="newspaper_article_list"),
    path("articles/<int:pk>/", views.article_detail, name="newspaper_article_detail"),
]

newspaper/urls.py
from django.urls import path

from . import views

app_name = "newspaper"

urlpatterns = [

    # Article urls
    path("", views.ArticleListView.as_view(), name="article_list"),
    path("<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/edit/", views.ArticleUpdateView.as_view(), name="article_edit"),
    path("<int:pk>/delete/", views.ArticleDeleteView.as_view(), name="article_delete"),
    path("new/", views.ArticleCreateView.as_view(), name="article_new"),

    # Comment urls
    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_new'),
    path("<int:pk>/comment/edit/", views.CommentUpdateView.as_view(), name="comment_edit"),
    path("<int:pk>/comment/delete/", views.CommentDeleteView.as_view(), name="comment_delete"),
]

newspaper/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    """Model representing an article published by a user."""
    
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="articles",
    )

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("newspaper:article_detail", kwargs={"pk": self.pk})


class Comment(models.Model):
    """Model representing a comment made on an article."""
    
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="comments",
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("newspaper:article_detail", kwargs={"pk": self.article.pk})

newspaper/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

newspaper/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model

from newspaper.models import Article
from .serializers import UserSerializer, ArticleSerializer


@api_view(["GET"])
def user_list(request):
    """Return a list of all users."""
    users = get_user_model().objects.all()
    serializer = UserSerializer(users, many=True)
    return Response(serializer.data)


@api_view(["GET", "POST"])
def article_list(request):
    """
    GET: Return a list of all articles.
    POST: Create a new article.
    """
    if request.method == "GET":
        articles = Article.objects.all()
        serializer = ArticleSerializer(articles, many=True)
        return Response(serializer.data)

    elif request.method == "POST":
        serializer = ArticleSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(["GET", "PUT", "DELETE"])
def article_detail(request, pk):
    """
    GET: Retrieve a specific article.
    PUT: Update an article.
    DELETE: Delete an article.
    """
    article = get_object_or_404(Article, pk=pk)

    if request.method == "GET":
        serializer = ArticleSerializer(article)
        return Response(serializer.data)

    elif request.method == "PUT":
        serializer = ArticleSerializer(article, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == "DELETE":
        article.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

newspaper/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy, reverse

from .forms import CommentForm
from .models import Article, Comment


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "newspaper/article_list.html"


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "newspaper/article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = (
        "title",
        "body",
    )
    template_name = "newspaper/article_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = "newspaper/article_delete.html"
    success_url = reverse_lazy("newspaper:article_list")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "newspaper/article_new.html"
    fields = ("title", "body")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("newspaper:article_list")


class CommentCreateView(LoginRequiredMixin, CreateView):
    form_class = CommentForm
    template_name = "newspaper/comment_new.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["article"] = get_object_or_404(Article, pk=self.kwargs["pk"])
        return context
    
    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs["pk"])
        form.instance.article = article
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("newspaper:article_detail", kwargs={"pk": self.kwargs["pk"]})
class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "newspaper/comment_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def get_success_url(self):
        return reverse("newspaper:article_detail", kwargs={"pk": self.object.article.pk})

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = "newspaper/comment_delete.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

    def get_success_url(self):
        return reverse("newspaper:article_detail", kwargs={"pk": self.object.article.pk})

newspaper/templates/newspaper/article_delete.html
{% extends "newspaper/layout.html" %}

{% block body %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ article.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock %}

newspaper/templates/newspaper/article_detail.html
{% extends "newspaper/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
    <div class="article-entry">
        <h2>{{ object.title }}</h2>
        <p>by {{ object.author }} | {{ object.date }}</p>
        <p>{{ object.body }}</p>
    </div>

    <hr>

    <h4>Comments</h4>
        {% for comment in article.comment_set.all %}
            <div class="comment">
                <p>
                    <strong>{{ comment.author }}</strong> &middot; {{ comment }}
                    {% if comment.author == user %}
                        <small>
                            <a href="{% url 'newspaper:comment_edit' comment.pk %}">Edit</a> |
                            <a href="{% url 'newspaper:comment_delete' comment.pk %}">Delete</a>
                        </small>
                    {% endif %}
                </p>
                <small class="text-muted">{{ comment.created_at|date:"F j, Y, g:i a" }}</small>
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}
    <hr>

    <h4>Add a comment</h4>
        <form action="{% url 'newspaper:comment_new' article.pk %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success ml-2" type="submit">Save</button>
        </form>

    <p>
        {% if article.author == user %}
            <a href="{% url 'newspaper:article_edit' article.pk %}">Edit Article</a> |
            <a href="{% url 'newspaper:article_delete' article.pk %}">Delete Article</a>
        {% endif %}
    </p>
    <p>Back to <a href="{% url 'newspaper:article_list' %}">All Articles</a>.</p>
{% endblock %}

newspaper/templates/newspaper/article_edit.html
{% extends "newspaper/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
    <h1>Edit</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>
{% endblock %}

newspaper/templates/newspaper/article_list.html
{% extends "newspaper/layout.html" %}

{% block title %}Articles{% endblock title %}

{% block body %}
    {% for article in article_list %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold">{{ article.title }}</span> &middot;
                <span class="text-muted">by {{ article.author }} |
                {{ article.date }}</span>
            </div>
            <div class="card-body">
                <p>{{ article.body }}</p>
                {% if article.author == request.user %}
                    <a href="{% url 'newspaper:article_edit' article.pk %}">Edit</a> |
                    <a href="{% url 'newspaper:article_delete' article.pk %}">Delete</a> |
                {% endif %}
                <a href="{{ article.get_absolute_url }}">View</a>
            </div>
            <div class="card-footer">
                {% for comment in article.comment_set.all %}
                    <p>
                    <span class="font-weight-bold">
                        {{ comment.author }} &middot;
                    </span>
                    {{ comment }}
                    </p>
                {% endfor %}
            </div>
        </div>
        <br />
    {% endfor %}
{% endblock %}

newspaper/templates/newspaper/article_new.html
{% extends "newspaper/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
    <h1>New article</h1>
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock %}

newspaper/templates/newspaper/comment_delete.html
{% extends "newspaper/layout.html" %}

{% block body %}
<div class="container">
    <h2>Delete Comment</h2>
    <p>Are you sure you want to delete this comment?</p>
    <div class="card">
        <div class="card-body">
            <p><strong>{{ comment.author }}</strong> on {{ comment.created_at|date:"F j, Y" }}</p>
            <p>{{ comment.comment }}</p>
        </div>
    </div>
    
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger ml-2" type="submit">Confirm Delete</button>
        <a href="{% url 'newspaper:article_detail' comment.article.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

newspaper/templates/newspaper/comment_edit.html
{% extends "newspaper/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
    <h2>Edit Comment</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Update</button>
        <a href="{% url 'newspaper:article_detail' comment.article.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

newspaper/templates/newspaper/comment_new.html
{% extends "newspaper/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
    <h2>Add a Comment</h2>
    <p>You are commenting on: <strong>{{ article.title }}</strong></p>
    
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success ml-2" type="submit">Save Comment</button>
        <a href="{% url 'newspaper:article_detail' article.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

newspaper/templates/newspaper/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <title>{% block title %}Newspaper App{% endblock %}</title>
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>

    <body>
        <div class="container">
            <header class="p-3 mb-3 border-bottom">
                <div class="container">
                    <div class="d-flex flex-wrap align-items-center justify-content-between">
                        <!-- Left: Brand -->
                        <a class="navbar-brand" href="{% url 'newspaper:article_list' %}">Newspaper</a>

                        <!-- Right: Buttons -->
                        {% if user.is_authenticated %}
                        <div class="d-flex align-items-center">
                            <a href="{% url 'newspaper:article_new' %}" class="nav-link px-2 link-dark">+ New</a>
                            <div class="dropdown text-end ms-3">
                                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
                                    id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username }}
                                </a>
                                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                    <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                                </ul>
                            </div>
                        </div>
                        {% else %}
                            <div class="text-end">
                                <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
                                <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </header>

            <main>
                {% block body %}
                {% endblock %}
            </main>
        </div>

        <!-- Bootstrap JavaScript Bundle -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    </body>
</html>