blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("post/new/", views.BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", views.BlogDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/edit/", views.BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", views.BlogDeleteView.as_view(), name="post_delete"),
    path("", views.BlogListView.as_view(), name="post_list"),
]

django_for_beginners/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("hello", include("hello_world.urls")),
    path("pages/", include("pages.urls")),
    path("messages/", include("message_board.urls")),
    path("blogs/", include("blog.urls")),
    path("newspaper/", include("newspaper.urls")),

    # API
    path("api/v1/", include("newspaper.api.urls")),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Post

# Create your views here.
class BlogListView(ListView):
    model = Post
    template_name = "blog/posts.html"

class BlogDetailView(DetailView):
    model = Post
    template_name = "blog/post.html"

class BlogCreateView(CreateView):
    model = Post
    template_name = "blog/post_new.html"
    fields = ["title", "author", "body"]

class BlogUpdateView(UpdateView):
    model = Post
    template_name = "blog/post_edit.html"
    fields = ["title", "body"]

class BlogDeleteView(DeleteView):
    model = Post
    template_name = "blog/post_delete.html"
    success_url = reverse_lazy("blog:post_list")

blog/templates/blog/layout.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <title>Django blog</title>
        <link rel="stylesheet" href="{% static 'blog/layout.css' %}">
        <link href="https://fonts.googleapis.com/css?family=\Source+Sans+Pro:400" rel="stylesheet">
    </head>
    <body>
        <div>
            <header>
                <div class="nav-left">
                    <h1><a href="{% url 'blog:post_list' %}">Django blog</a></h1>
                </div>
                <div class="nav-right">
                    <a href="{% url 'blog:post_new' %}">+ New Blog Post</a>
                </div>
            </header>

            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

blog/templates/blog/post.html
{% extends "blog/layout.html" %}

{% block body %}
    <div class="post-entry">
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
    </div>

    <a href="{% url 'blog:post_edit' post.pk %}">+ Edit Blog Post</a>
    <a href="{% url 'blog:post_delete' post.pk %}">+ Delete Blog Post</a>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends "blog/layout.html" %}

{% block body %}
    <h1>Delete post</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}?</p>
        <input type="submit" value="confirm">
    </form>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends "blog/layout.html" %}

{% block body %}
    <h1>Edit post</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

blog/templates/blog/post_new.html
{% extends "blog/layout.html" %}

{% block body %}
    <h1>New post</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

blog/templates/blog/posts.html
{% extends "blog/layout.html" %}

{% block body %}
    {% for post in post_list %}
        <div class="post-entry">
            <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.body }}</p>
        </div>
    {% endfor %}
{% endblock %}