blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("post/new/", views.BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/", views.BlogDetailView.as_view(), name="post_detail"),
    path("post/<int:pk>/edit/", views.BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", views.BlogDeleteView.as_view(), name="post_delete"),
    path("", views.BlogListView.as_view(), name="post_list"),
]

django_for_beginners/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("hello", include("hello_world.urls")),
    path("pages/", include("pages.urls")),
    path("messages/", include("message_board.urls")),
    path("blogs/", include("blog.urls")),
    path("newspaper/", include("newspaper.urls")),

    # API
    path("api/v1/", include("newspaper.api.urls")),
]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutPageView.as_view(), name="about"),
]

pages/templates/pages/about.html
{% extends "pages/layout.html" %}

{% block body %}
    <h1>About page</h1>
{% endblock %}

pages/templates/pages/home.html
{% extends "pages/layout.html" %}

{% block body %}
    <h1>Home page</h1>
{% endblock %}

pages/templates/pages/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Pages</title>
    </head>
    <body>
        <header>
            <a href="{% url 'pages:home' %}">Home</a>
            <a href="{% url 'pages:about' %}">About</a>
        </header>
        {% block body %}
        {% endblock %}
    </body>
</html>